
<PopUpDel>:

    btn_nodel: btn_nodel
    btn_yesdel: btn_yesdel

    size_hint: .5, .5
    auto_dismiss: True
    title: 'Delete'

    BoxLayout:
        orientation: 'vertical'

        Label:
            text: 'Delete chunk?'

        BoxLayout:
            orientation: 'horizontal'

            Button:
                id: btn_yesdel
                text: 'YES'
            Button:
                id: btn_nodel
                text: 'NO'











